#!/usr/bin/env bash
folder="/home/potato/Desktop/Disk"
bochsFolder="/home/potato/Desktop/Bochs Folder"
src="$folder/src"
bin="$folder/bin"
cd "$folder"
nasm -f bin "$src/disk.asm" -l memory.lst -o "$bin/disk"
sudo dd if="$bin/disk" of="$bochsFolder/test.iso" bs=512 count=1 | hexdump -C
sudo chmod u=rwx,g=rwx,o=rwx "$bochsFolder/test.iso"
cd "$bochsFolder"
bochs
$SHELL
